@startuml
|学生|
|系主任|
|教师|
|教务处|
:安排考试;
:考试安排表;
|教师|
:出卷;
split
 :打印审批卷]
 |系主任|
 :审批签字;
 :打印审批表;
split again
 |教师|
  :A·B试卷]
  end split
 |教务处|
  :打印试卷;
  :试卷;
|学生|
:参加考试;
:答卷;
|教师|
:阅卷出成绩;
split
:答卷;
:装订存档]
split again
:成绩单;
|教务处|
if (有不及格?) then (有)
:安排补考;
:补考安排表]
endif
end split
:期末流程结束;
@enduml