@startuml

object 用户 {
  用户ID = 11111
  用户密码 = 11111
  其他用户信息 = fdsfadsad
  注册日期 = 2018.1.1
}
object 书籍 {
 书本id =22222
 书名 = 虚拟机
 作者 = 作者
 购买日期 = 2018.1.1
}
object 借书记录 {
  借书日期 = 2018.2.2
  归还日期 = 2018.3.2
  管理员处理情况 = true
}
object 记录{
   流水号 = 33333
   书本号 = 22222
   借阅者id = 11111
}
object 预定记录 {
    预定日期 = 2018.5.5
    预定过期日期 = 2018.5.6
}
object 管理员 {
  管理员ID = 99999
  密码 = 99999
  姓名 = 管理
}

@enduml