@startuml
object 借书记录 {
  借书日期 = 2018.2.2
  归还日期 = 2018.3.2
  管理员处理情况 = true
}
object 记录{
   流水号 = 33333
   书本号 = 22222
   借阅者id = 11111
}
object 预定记录 {
    预定日期 = 2018.5.5
    预定过期日期 = 2018.5.6
}
借书记录--|>记录
预定记录--|>记录
@enduml